### ISSUE TITLE
Cannot find hstspreload.bin when bundled with PyInstaller

### ISSUE THREAD

**Issue by sethmlarson** [sethmlarson/hstspreload#2]
See: https://mystb.in/cipiparicu.py

```python
Traceback (most recent call last):
  File "main.py", line 113, in <module>
  File "click/core.py", line 764, in __call__
  File "click/core.py", line 717, in main
  File "click/core.py", line 1137, in invoke
  File "click/core.py", line 956, in invoke
  File "click/core.py", line 555, in invoke
  File "main.py", line 47, in cmd_download
  File "main.py", line 108, in extract_direct_download_links
  File "main.py", line 97, in do_download
  File "anido/stream_downloader.py", line 50, in download
  File "anido/stream_downloader.py", line 39, in stream
  File "httpx/client.py", line 820, in get
  File "httpx/client.py", line 725, in request
  File "httpx/client.py", line 324, in build_request
  File "httpx/client.py", line 164, in merge_url
  File "hstspreload/__init__.py", line 88, in in_hsts_preload
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/vr/qsr1bv8j2cs6g7zkkx3x9ggh0000gn/T/_MEI0GSWAu/hstspreload/hstspreload.bin'
```

**Comment by denravonska** [comment]
So, what's the workaround for this?
